apiVersion: v1
kind: Pod
metadata:
  name: sample-dnspolicy-clusterfirst
  labels:
    name: myapp
spec:
  dnsPolicy: ClusterFirst
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "10m"
