apiVersion: v1
kind: Pod
metadata:
  name: sample-ep
spec:
  containers:
  - name: nginx-ep
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "10m"
    command: ["/bin/sleep"]
    args:
      - "3600"