apiVersion: v1
kind: Pod
metadata:
  name: sample-2pod-fail
spec:
  containers:
  - name: nginx1
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "10m"
  - name: nginx2
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "10m"
