apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-complex-scheduling
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # 필수조건
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd
                  - nvme
      preferredDuringSchedulingIgnoredDuringExecution: # 우선조건
        - weight: 1 # 값이 높을 수록 더 우선으로 적용 됨3333333333333333333
          preference:
            matchExpressions:
              - key: cpu
                operator: Gt
                values:
                  - 2
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # 필수조건
        - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - sample-pod
          topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # 필수조건
        - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - sample-pod
          topologyKey: kubernetes.io/hostname
  containers:
    - name: nginx-container
      image: nginx:1.16

