apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-affinity-host
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key:  app
                operator: In
                values:
                  - sample-app
          topologyKey: kubernetes.io/hostname # app: sample-app레이블을 가진 파드가 실행되는 노드의 호스트네임과 같은 값을 가진 노드에 스케줄링 한다.
  containers:
    - name: nginx-container
      image: nginx:1.16