version: '3'
services:
  go:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - 'db'
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: usr
      MYSQL_PASSWORD: password
      TZ: 'Asiz/Seoul'
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
