# additionalArguments:
#   - "--tracing.jaeger=true"
#   - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.default.svc:5778/sampling"
#   - "--tracing.jaeger.localAgentHostPort=jaeger-agent.default.svc:6831"


providers:
  kubernetesCRD:
    allowCrossNamespace: true

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  jaeger:
    port: 1234
    expose: true
    exposedPort: 1234
    protocol: TCP

# tracing:
#   jaeger:
#     propagation: jaeger
#     localAgentHostPort: jaeger-agent.default.svc:6831
#     samplingServerURL: http://jaeger-agent.default.svc:5778/sampling